swipe:
  3: 
    left: 
      command: 'xdotool key super+d'
    right: 
      command: 'xdotool key super+d'
    up:
      command: 'xdotool key ctrl+alt+Up'
    down: 
      command: 'xdotool key ctrl+alt+Down'
  4:
    left: 
      command: 'xdotool key ctrl+alt+Up'
    right: 
      command: 'xdotool key ctrl+alt+Down'
    up: 
      command: 'xdotool key ctrl+alt+Up'
    down: 
      command: 'xdotool key ctrl+alt+Down'
pinch:
  in:
    command: 'xdotool key ctrl+plus'
  out:
     command: 'xdotool key ctrl+minus'

threshold:
  swipe: 0.4
  pinch: 0.4

interval:
  swipe: 0.8
  pinch: 0.1

